# Generated by Django 3.0.7 on 2020-09-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
