# Generated by Django 3.0.7 on 2020-09-27 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0005_auto_20200927_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default=25, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photo_album.Photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
