# Generated by Django 3.0.7 on 2020-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0006_auto_20200927_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
