# Generated by Django 3.0.7 on 2020-09-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0007_photo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
