# Generated by Django 3.0.7 on 2020-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_album', '0008_auto_20200927_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
